### ISSUE TITLE
Mp compatibility 

### ISSUE THREAD

**Issue by Nutelaspaceman** [RealzPrestige/fire#2]
for some reason it stopped working with: rh, future and earthhack, works on sp but as soon as i join a server crashes

you prob have abandoned the project so idk

**Comment by Zane2b2t** [comment]
Use a mixinbooter with ! Infront of the name

**Comment by Zane2b2t** [comment]
> for some reason it stopped working with: rh, future and earthhack, works on sp but as soon as i join a server crashes
> 
> you prob have abandoned the project so idk

"Stopped working" meaning it used to work b4?
Maybe try the leak or this with gentkeman's PR removed idk

**Comment by RealzPrestige** [comment]
> "Stopped working" meaning it used to work b4? Maybe try the leak or this with gentkeman's PR removed idk
Gentleman only changed the gui animations, I have never used earthhack before so it might be that, also looking at previous commits it seems like ive tried to fix compatibility with rusher so that might also be it.

**Comment by Zane2b2t** [comment]
> 

The leak worked with earthhack ive never used the official version idk @Nutelaspaceman send crashlog
